### ISSUE TITLE
No module named UW

### ISSUE THREAD

**Issue by jeffin07** [BIGWangYuDong/UWEnhancement#2]
Hi,
First of all great effort.
When i tried to run the test_UWModels/test_UIEC2Net.py it shows the error `No module named UW`.I have already renamed the repo to UW. Can you please tell me what might be the cause?

python: 3.6
PyTorch :1.8

**Comment by BIGWangYuDong** [comment]
Hi,
Firstly, please refer [getting_start](https://github.com/BIGWangYuDong/UWEnhancement/blob/master/docs/getting_start.md) to install environment.
Second, you can remove UW. then it can run

Best regards,
Dong

**Comment by jeffin07** [comment]
@BIGWangYuDong 
Thank you for your reply. I did follow the instructions in getting_start to install the environment. The installation was successful but it still shows no module named UW. Did you ever encounter this problem? .Also one more thing I get this when I run test_xxx.py in test_UWModels

**Comment by BIGWangYuDong** [comment]
You can remove UW. then it can work. I have tried this.

**Comment by jeffin07** [comment]
@BIGWangYuDong Can you please explain what do you mean by removing UW?

**Comment by BIGWangYuDong** [comment]
For example
`from UW.core.Models.builder import NETWORK, build_backbone` 
You can remove UW and try to run the test file.

**Comment by jeffin07** [comment]
@BIGWangYuDong Thank you. It's working perfectly. Before I close this issue can I ask you why this approach we can completely remove UW from all the files why makes a confusion? is there any specific reason. Also, I noticed a lot of operation in Cuda can we make that compatible for CPU also for testing scripts. Is it okay if I raise a PR for rectifying these issues?

**Comment by BIGWangYuDong** [comment]
I have no idea why this problem happened, I think if remove .cuda() (for example model.cuda()) then it can run in CPU. Its easy to make the code run in CPU

**Comment by jeffin07** [comment]
@BIGWangYuDong yeah, it's that simple, I just asked because it was hardcoded.If it was generalized it will be more helpful.Thank you for the response and great job :+1:

**Comment by BIGWangYuDong** [comment]
@jeffin07 I think maybe you can use gpus=0 to run the code on cpu, I did not try this, but I think it can work. I refer mmdetection to write this repo.

**Comment by BIGWangYuDong** [comment]
And if you want to debug this code, you can set works_per_gpu=0
