### ISSUE TITLE
HSV loss

### ISSUE THREAD

**Issue by jjkbjj** [BIGWangYuDong/UWEnhancement#5]
Hello! We are very interested in the work you have done, but we don’t know how to implement the HSV loss code mentioned in your paper. I hope you can answer and look forward to your reply.

**Comment by BIGWangYuDong** [comment]
Hi, I forgot to sync the HSV Loss in this repo, I'll do it later

**Comment by BIGWangYuDong** [comment]
https://github.com/BIGWangYuDong/UWEnhancement/pull/10
