### ISSUE TITLE
where is importlib._setup()

### ISSUE THREAD

**Issue by MaDaJie2706** [BIGWangYuDong/UWEnhancement#6]
First of all, thank you very much for sharing! When I run train.py, it has the error shown in the image below.And I tried to run _bootstrap_external.py.But I can't find importlib._setup()
![image](https://user-images.githubusercontent.com/60532942/134516614-68339968-ddc6-4a49-a885-f03cdcf66642.png)
![image](https://user-images.githubusercontent.com/60532942/134518669-596597f4-6e0f-4b6e-86e4-dcd447db6682.png)

**Comment by BIGWangYuDong** [comment]
I did not meet this error before, more details is needed, such as your environment,

**Comment by MaDaJie2706** [comment]
@ BIGWangYuDong Thank you very much for your reply! This is my running environment.
![运行环境](https://user-images.githubusercontent.com/60532942/134528588-9032308d-b049-465c-bdde-0657c17432ee.png)

**Comment by BIGWangYuDong** [comment]
Did you install your environment followed by [getting_start](https://github.com/BIGWangYuDong/UWEnhancement/blob/master/docs/getting_start.md)? and under ubuntu?

**Comment by BIGWangYuDong** [comment]
it is suggested to re-install the environment under ubuntu.

**Comment by MaDaJie2706** [comment]
@BIGWangYuDong  OK,I will try it.Thank you again!
